### ISSUE TITLE
Fix site for mobiles

### ISSUE THREAD

**Issue by thc202** [zaproxy/zaproxy-website#3] opened 2020-01-27 14:12 UTC
psiinon wrote:
```
I've had a look at the site in Firefox reactive mode and it could definitely be improved!
The header and footer dont look good on larger mobile screens.
The hamburger menu only appears on smaller screens and works better, but the text is probably too big.
We should probably simplify the footer for mobiles, maybe removing most of the links?
```

```
Header and footer hopefully fixed by #81
```

**Comment by kingthorin** [comment] 2020-02-06 19:35
On mobile (portrait mode) the user guide index appears before content so you have to scroll way way way down to get to the content you want (as a user).

**Comment by kingthorin** [comment] 2020-04-21 11:53
Maybe a hamburger menu could be used similar to the API docs.

**Comment by kingthorin** [comment] 2021-04-05 17:19
I believe the User Guide index/tic thing was fixed, so can this now be closed?

**Comment by thc202** [comment] 2021-04-05 17:22
Sounds good to me.

**Comment by psiinon** [comment] 2021-04-06 08:22
Hum, works fine on my phone in portrait mode but not landscape.
So I think it still needs a tweek...

**Comment by njmulsqb** [comment] 2023-03-19 14:00
Hi,
@psiinon Can you mention what are the current UI issues with the website's mobile version?

**Comment by psiinon** [comment] 2023-03-20 10:14
@njmulsqb try it and see? 😁 
You can always use Firefox Responsive Design Mode on a computer if thats easier that using a mobile..

**Comment by njmulsqb** [comment] 2023-03-22 05:30
On landing page, I can see one thing only, there should be a spacing between these two buttons
![image](https://user-images.githubusercontent.com/47940898/226811136-634de666-11c1-4d6c-a65f-30486d665837.png)

**Comment by kingthorin** [comment] 2023-03-22 15:05
As Simon pointed out, we don't currently have a list of things. Feel free to start with the buttons and look around for other stuff :wink:

**Comment by Moeez905** [comment] 2023-04-30 15:17
Hi all,
@njmulsqb directed me to this. I am a self learnt frontend developer and I am willing to work on this issue and close out all the responsive issues. Can you assign this issue to me?
P.s. expect lots and lots of queries from me as I am not well versed with git concepts so it will be a great learning experience for me as well :)

**Comment by Moeez905** [comment] 2023-05-04 07:01
Hi all,
I have tried using git remote add & gitch fetch upstream commands but the issue is still there!
kindly let me know which cmd will work for this.
thanks,

**Comment by Moeez905** [comment] 2023-05-07 06:58
> The hamburger menu only appears on smaller screens and works better, but the text is probably too big.
Now I'm willing to take on this, what font size should I go for? Got any preferences?

**Comment by Moeez905** [comment] 2023-05-07 07:22
I've just noticed that the footer is missing in mobile view, is it left intentionally?

**Comment by thc202** [comment] 2023-05-08 05:54
I'd say most likely:
> We should probably simplify the footer for mobiles, maybe removing most of the links?

**Comment by Moeez905** [comment] 2023-05-09 04:31
After Buttons and Hamburger adjustments in mobile view, now I'm going to work on footer, that's currently not visible on smaller screens 

>  We should probably simplify the footer for mobiles, maybe removing most of the links?

**Comment by Moeez905** [comment] 2023-07-10 13:54
Thank you so much everyone for your time and exceptional guidance and support!

I hope you guys are satisfied with my tiny contribution and I'd like to have suggestions from you guys regarding things that I need to improve or work on.
Besides everything, all front-end and mobile responsiveness issues have been addressed and merged successfully I think, if it really is so we can close this category altogether as resolved.

Thank you 💙
@kingthorin @thc202 @njmulsqb @psiinon & everyone

**Comment by Moeez905** [comment] 2023-08-08 13:01
Congratulation team for successfully merging into SSP!
Let me know if mobile issues are still relevant or if they need any further adjustments otherwise, this issue can be closed.

**Comment by psiinon** [comment] 2024-01-16 09:47
@Moeez905 do you think the site is ok for mobiles now? 😁

**Comment by Moeez905** [comment] 2024-01-19 21:31
> @Moeez905 do you think the site is ok for mobiles now? 😁

Yeah it seems fine - We can close this issue

**Closed** 2024-01-22 09:48 UTC
